use environment variable to force install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -7,38 +7,15 @@ bold=`tput bold`
 normal=`tput sgr0`
 end_color='\033[0;m'
 
-print_usage() {
-  echo -e "Unsupported option: $@"
-  echo -e "Supported options:"
-  echo -e "\t-f, --force          \tReplace existing vim installation."
-}
-
-FORCE=0
-
-while [[ $# > 0 ]]
-do
-  key="$1"
-
-  case $key in
-    -f|--force)
-      FORCE=1
-      shift
-      ;;
-    *)
-      print_usage $key
-      exit 1
-      ;;
-  esac
-  shift
-done
+FORCE=${FORCE:-0}
 
 if [ -d "$HOME/.vim" ]; then
-  if [ $FORCE == 0 ]; then
-    echo -e "${red}${bold}ERROR${end_color}: Found existing vim config. Aborting${end_color}"
-    exit 1
-  else
-    echo -e "${yellow}${bold}WARN${end_color}: Moving existing vim config to $HOME/.vim.old${end_color}"
+  if [ $FORCE == 1 ]; then
+    echo -e "${yellow}${bold}WARN${end_color}: Moving existing vim config to $HOME/.vim.old"
     mv $HOME/.vim $HOME/.vim.old
+  else
+    echo -e "${red}${bold}ERROR${end_color}: Found existing vim config. Aborting. Run with FORCE=1 to override"
+    exit 1
   fi
 fi
 
